### ISSUE TITLE
Annotating precursor peak.

### ISSUE THREAD

**Issue by jopoehls** [bittremieux/spectrum_utils#31]
Hi,
I would like to have the precursor peak annotated as well in the plotted spectrum. If this is already possible, please tell me how and I am gone immediately, but it seems 'ion_types' can only be [abcxyz]. 
Is it possible to implement this? There seems to be already a functionality to detect the precursor peak based on the calculated mass and the tolerance, so I am hoping it would mostly be about the visualisation.
Anyways, thanks for the great work on this!

Jonas

**Comment by bittremieux** [comment]
Hi Jonas, the latest version v0.3.5 indeed only annotates a,b,c,x,y,z ions. Precursor peak annotation has already been implemented, but the new code has not been published in a new release yet because I still need to finish up some unit tests and documentation. This functionality will become available relatively soon.
