### ISSUE TITLE
latex dependency?

### ISSUE THREAD

**Issue by justinjjvanderhooft** [bittremieux/spectrum_utils#6]
Hi Wout,

I was trying the example notebook and I got the below error message after reading in the spectrum - is there a dependency on latex somewhere to plot a spectrum?

A tip is to include the minimum version numbers - I had a slightly older version of thepyteomics package that did not include the get_mgf functionality you are using.

Cheers Justin

```
plot.spectrum(spec)

plt.show()
plt.close()
```
returned: FileNotFoundError: [Errno 2] No such file or directory: 'latex': 'latex'

**Comment by bittremieux** [comment]
The notebook indeed uses some LaTeX functionality, more precisely for styling the plot titles (different font sizes, etc.). Typically you won't need this functionality, I just wanted it to look a bit nicer than you can get with Matplotlib only.

So you need to either have LaTeX on the path to run the notebook, or you need to disable the second cell to not use LaTeX. (In the latter case the plot titles will look weird because they contain LaTeX commands, but it should run.)

I need to extend the documentation to make that clear and to demonstrate additional functionality.

**Comment by justinjjvanderhooft** [comment]
Thanks Wout. The spectrum without any filtering does plot now!

However, I get a Typing error when applying the filtering relating to line 258 in the spectrum.py file (see below). Looks like numba expects something different (https://numba.pydata.org/numba-doc/dev/user/troubleshoot.html) but I don't know what. And assuming it works okay at your end, it could be a versioning issue with one of the required packages as well.

'''
TypingError: Failed at nopython (nopython frontend)
Invalid usage of == with parameters (str, const('Da'))
'''

**Comment by bittremieux** [comment]
Using strings in Numba-compiled functions is a bit tricky. Limited string support has only been added to Numba in [version 0.41](https://numba.pydata.org/numba-doc/dev/release-notes.html#version-0-41-0). So if you're using an older version you should probably just update Numba. On my end it works without any problems with Numba 0.45.

I'm adding this minimum Numba version to the dependency requirements. Thanks for reporting.

**Comment by justinjjvanderhooft** [comment]
Indeed, now the matplotlib plotting is working fine! Thanks Wout.

**Comment by bittremieux** [comment]
Great. The minimum Numba dependency will be specified in the next release. I'm not putting a minimum Pyteomics version because the MGF IO isn't part of the core spectrum_utils functionality, I just used it in the notebook to read the spectral data.

Let me know if you have further questions or comments. :)
