### ISSUE TITLE
numba version issue

### ISSUE THREAD

**Issue by oliveralka** [bittremieux/spectrum_utils#7]
Hello, 
I am currently playing around with the toolbox and its visualization capabilities - thank you!

I ran into a few smaller issues and wanted to report them here: 

I installed spectrum_utils from git:
`pip install git+https://github.com/bittremieux/spectrum_utils`

One issue was that the rdkit dependency was missing: 
`conda install -c conda-forge rdkit`

I ran into another issue regarding numba version 0.45.1 (due to the deprication of the "reflection list"):
```
/usr/local/miniconda3/envs/test_py37/lib/python3.7/site-packages/numba/ir_utils.py:1959: NumbaPendingDeprecationWarning: 
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'annotation_mz' of function '_get_peptide_fragment_annotation_map'.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types

File "../../../../../../usr/local/miniconda3/envs/test_py37/lib/python3.7/site-packages/spectrum_utils/spectrum.py", line 507:
@nb.njit
def _get_peptide_fragment_annotation_map(
^

  warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))

Process finished with exit code 0
```

I "fixed" it by installing the numba version 0.42.1

`pip install numba==0.42.1`

**Comment by bittremieux** [comment]
Yes indeed, RDKit isn't specified as a dependency in `setup.py` because you can't install it from PyPI, only using conda. That's why conda is the recommended method of installation mentioned in the README, but I can make it a bit more clear that otherwise RDKit needs to be installed explicitly by the user.
I'm going to put out a new version this week and the bioconda recipe will be updated accordingly, so that will allow easy installation of the latest version using conda again.

I'm aware of the deprecation warning by Numba. It's a warning because in the future some Numba internals will change. My code should work with the old as well as the upcoming new Numba functionality without needing to be changed, so for the time being that warning can be safely ignored. I'll make a note of it in the README as well to avoid any confusion.

Be sure to let me know if you have any further comments or feature requests. ☺️

**Comment by oliveralka** [comment]
Ok, thanks a lot - no feature requests for now!
