### ISSUE TITLE
Peak(s) not annotated within correct ppm

### ISSUE THREAD

**Issue by gpdann** [bittremieux/spectrum_utils#8]
Hi,

I am using spectrum_utils to annotate spectra from an mzML file.  I've noticed that certain peaks are not annotated when the fragment_tol_mass/fragment_tol_mode are set to correctly identify them.  I've pasted a DropBox link with my code, mzML file, and a Powerpoint file with two spectra displaying the issue.  The base peak in the spectrum I've chosen is the peptides b7+ ion, which I've verified from the raw data is 2-3 ppm off of the theoretical mass.  The peak isn't annotated when the fragment_tol_mass is set to 10 ppm.  It is annotated, however, when the fragment_tol_mass is set to 20 ppm.

Thanks,

Geoff

https://www.dropbox.com/sh/feoss7jqra5fsil/AACoHcZ9umTJQ3OnF6hVxcfJa?dl=0

**Comment by bittremieux** [comment]
Hi Geoff, thank you for supplying your code and data, it made it easy to investigate this issue.

According to my calculation the ppm error for the y7+ peak (I think you mean this one) is 10.047 ppm. So this is an edge case and if some other software rounds the masses you might see a different result. Increasing the ppm tolerance in your code snippet to 10.1 ppm indeed annotates the y7+ peak as well.

You mention 2–3 ppm, so for clarity I include my calculation below:

- Theoretical mass y7+ (as [calculated by Pyteomics](https://pyteomics.readthedocs.io/en/latest/mass.html#faster-mass-calculations)): 802.3399611504701
- Experimental mass: 802.3319
- ppm difference: (802.3399611504701-802.3319)/802.3399611504701*1000000 = 10.04705095149588

This is really an edge case, because if you round the theoretical mass to the same precision as the observed mass, the ppm error would actually be 9.97 ppm.
But it doesn't seem like there's a bug in the code based on my calculations.

**Comment by gpdann** [comment]
Hi Wout,

Thanks so much for taking a look.  What a dumb thing for me to mess up.  I
will look into the tool I was using to calculate the theoretical mass of
the fragment and see if there is something I missed.  Thanks again!

Geoff
