### ISSUE TITLE
rdkit dependency not installed 

### ISSUE THREAD

**Issue by lgatto** [bittremieux/spectrum_utils#9]
Hi Wout - when installing `spectrum_utils` using conda with 
```
conda install -c bioconda spectrum_utils
```
as suggested [here](https://spectrum-utils.readthedocs.io/en/latest/install.html), I noted that `RDkit` didn't install automatically, as advertised on the page. I had to manually
```
conda install -c conda-forge rdkit
```
to get `spectrum_utils` to work.
Hope this helps.

**Comment by bittremieux** [comment]
That's weird; I just tried to install `spectrum_utils` in a clean conda environment and all dependencies got automatically installed as well, as expected.

All the other dependencies were installed correctly? There shouldn't be anything special about RDKit compared to those, so I'm not sure what's going on.

Which conda version are you using and which Python version in the conda environment? What is the channel preference for conda?

**Comment by lgatto** [comment]
Here's what I used for the installation:
```
$  bin ./conda --version
conda 4.7.12
```
and
```
(py36) $ python --version
Python 3.6.9 :: Anaconda, Inc.
```
This was also a fresh install. I hadn't set any channels or any channel priorities. 

As far as I can say, all other dependencies installed correctly - at least I didn't get any error messages, except for a missing RDkit.

**Comment by bittremieux** [comment]
Apparently not explicitly specifying the conda-forge channel misses dependencies that need to be retrieved from there. I'd set up global channel priorities, which is why I didn't run into that problem.

You can install `spectrum_utils` and all dependencies using the following command:

`conda install -c conda-forge -c bioconda -c defaults spectrum_utils`

The documentation has been updated accordingly.

Thank you for reporting this issue.
